# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('star', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
