# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
