# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20170812_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('star', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 12, 22, 31, 2, 867851))),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_date',
        ),
        migrations.AddField(
            model_name='house',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 22, 31, 2, 866850)),
        ),
        migrations.AddField(
            model_name='comment',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Main.House'),
        ),
    ]
