# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 08:03
from __future__ import unicode_literals

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20170812_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='house',
            name='date',
        ),
        migrations.AddField(
            model_name='house',
            name='photo',
            field=models.ImageField(blank=True, default=True, upload_to=Main.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
